pull_request_rules:
  - name: Approve and merge non-major version dependabot upgrades
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success~=lint
      - title~=^build\(deps[^)]*\). bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      review:
        type: APPROVE
      merge:
        method: squash

  - name: Approve and merge Snyk.io upgrades
    conditions:
      - author=snyk-bot
      - check-success~=lint
      - title~=^\[Snyk\]
    actions:
      review:
        type: APPROVE
      merge:
        method: squash

  - name: Close stale PRs (>1 month since last activity)
    conditions:
      - updated-at>30 days ago
    actions:
      close:
        message: This pull request has been closed as it has been a month since the most recent activity on it.

  - name: Automatically delete branches after they have been merged
    conditions:
      - merged
    actions:
      delete_head_branch:

  - name: Automatically mark a PR as draft if [WIP] is in the title
    conditions:
      - title~=(?i)\[wip\]
    actions:
      edit:
        draft: True
